### PR TITLE
java-velocypack #12 - Support for heterogeneous arrays

### PR DESCRIPTION
**Pull request by wajda**
This pull request adds support for heterogenous arrays. See #12

### CODE REVIEW

**Comment by OmarAyo** [comment]
Hi @wajda 

Many thanks for contributing. We are obliged by law to have a signed scanned copy of a Contributor License Agreement (CLA) to be able to accept pull requests to the official ArangoDB repository - even for such small changes.

We use an Apache 2 CLA for ArangoDB and its companion projects, which can be found here: https://www.arangodb.com/documents/cla.pdf
Just fill in the form, sign and send a scanned copy over to cla@arangodb.com

Thank you

**Comment by wajda** [comment]
Hi @OmarAyo,
I just signed and mailed the CLA.

**Comment by OmarAyo** [comment]
Hi @wajda 

I am not able to see your CLA, did you send it to cla@arangodb.com?

**Comment by wajda** [comment]
Yes, I sent it on Friday, 26 April 2019 at 16:39 CET. The mail should be sent from @eoh-europe.cz address.

**Comment by wajda** [comment]
Hi guys, is there anything from your side that prevents this PR from been merged?

**Comment by OmarAyo** [comment]
Hi @wajda 

Unfortunately, we are did not receive any signed CLA from you. Can you try to send it via fax. You can find the info directly inside the CLA you signed 

Best,

**Comment by wajda** [comment]
Hi @OmarAyo 
It seemed to be an issue with my working email that day. I just resent the CLA from my private email. Please check.

**Comment by OmarAyo** [comment]
CLA available

**Comment by wajda** [comment]
@OmarAyo, can we merge it or is there anything else that needs to be done?

**Comment by wajda** [comment]
Guys I see some changes were made by you in the upstream, but my pull request remains unattended. Is this PR still valid or you have resolved the issue in another way?

**Comment by rashtao** [comment]
Hi @wajda, thanks for the reminder! Your code seems OK to me, but I would like to take some time to review the APIs exposed by the library to support type hints. I will likely merge it in the next weeks.

**Pull request merged**
